# Use root/example as user/password credentials
version: "3.1"

services:
  mysql_db:
    image: mysql:5.7
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - C:\Users\Yun\Documents\ServerDocker\meeting\mysql:/var/run/mysqld
      # - /my_sql:/var/run/mysqld
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: meeting_room_prod
    networks:
      - meetings
    ports:
      - 3308:3306
  
networks:
  meetings:
